const Discord = require(`discord.js`)
exports.run = (client, msg) => {
    const user = msg.mentions.users.first()
    if(msg.mentions.users.size === 0) return msg.channel.send(`-User is a required argument.`, {code: "diff"})
    if (msg.mentions.users.first().id === msg.author.id) return msg.channel.send(`@ I know you love yourself, but...`, {code: "py"})
    if (msg.mentions.users.first().id === "238711670057336842") return msg.channel.send(`@ What are you trying? He is mine!`, {code: "py"})
    if (msg.mentions.users.first().id === `298463497715580948`) return msg.channel.send(`@ What are you trying? I am not yours!`, {code: "py"})
    function ship(){
      var relationship = [
        `[ ${user.username} hate you ${msg.member.user.username} ]`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 1%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 2%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 3%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 4%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 5%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 6%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 7%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 8%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 9%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 10%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 11%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 12%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 13%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 14%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 15%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 16%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 17%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 18%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 19%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 20%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 21%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 22%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 23%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 24%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 25%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 26%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 27%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 28%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 29%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 30%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 31%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 32%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 33%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 34%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 35%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 36%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 37%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 38%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 39%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 40%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 41%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 42%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 43%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 44%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 45%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 46%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 47%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 48%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 49%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 50%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 51%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 52%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 53%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 54%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 55%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 56%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 57%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 58%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 59%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 60%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 61%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 62%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 63%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 64%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 65%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 66%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 67%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 68%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 69%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 70%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 71%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 72%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 73%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 74%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 75%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 76%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 77%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 78%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 79%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 80%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 81%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 82%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 83%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 84%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 85%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 86%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 87%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 88%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 89%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 90%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 91%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 92%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 93%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 94%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 95%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 96%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 97%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 98%`,
        `[ ${msg.member.user.username} ] ❤ [ ${user.username} ] ; 99%`,
        `[ ${user.username} is your soul mate ${msg.member.user.username} ]`,

  ];
  var RN = Math.floor(Math.random()*relationship.length);
  return relationship[RN]
  }
  msg.channel.send(ship(), {code: "ini"})
}

exports.conf = {
  enabled: true,
  runIn: ["text", "dm", "group"],
  aliases: [],
  permLevel: 0,
  botPerms: [],
  requiredFuncs: [],
};

exports.help = {
  name: "ship",
  description: "% relationship",
  usage: "",
  usageDelim: " ",
};